import { MetadataRoute } from 'next';
import { siteConfig } from '@/data/siteConfig';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.title,
    short_name: siteConfig.title,
    description: siteConfig.description,
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#000000',
    icons: [
      {
        src: '/favicon.ico',
        sizes: 'any',
        type: 'image/x-icon',
      },
      {
        src: '/icon', // Auto-generated by app/icon.tsx
        sizes: '32x32',
        type: 'image/png',
      },
      {
        src: '/apple-icon', // Auto-generated by app/apple-icon.tsx
        sizes: '180x180',
        type: 'image/png',
      }
    ],
  };
}